# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UploadImageToDrive' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UploadImageToDrive

    #pod 'GoogleAPIClientForREST', '1.3'
    #pod 'GoogleAPIClientForREST/Drive', '1.3'
    #pod 'GTMAppAuth', '1.0'
    #pod 'AppAuth', '1.2'

end
